# --------------------------------------------------------------------------------------------------
# Notes:
# - jobs are executed in the order indicated at root "stages" property
# - "needs" property needs an array of job names (not stages names)
# - linter needs install:dev as eslint and prettier are dev dependencies
# --------------------------------------------------------------------------------------------------
stages:
  - quality
  - pack_prod

# This folder is cached between builds
default:
  cache:
    paths:
      - node_modules/
  before_script:
    - |
      {
        echo "@aqmo.org:registry=${CI_API_V4_URL}/projects/59/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/59/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc

quality:dev:
  stage: quality
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: manual
  tags:
    - nodejs-20
  variables:
    NODE_ENV: development
  script:
    - npm i
    - npm run lint

pack:prod:
  stage: pack_prod
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: manual
  tags:
    - nodejs
  variables:
    NODE_ENV: production
  script:
    - npm i
    - npm pack
  artifacts:
    name: 'rudi_media.tgz'
    when: on_success
    paths:
      - ./rudi_media_drv-*.tgz
